openapi: 3.0.2
info:
  version: 1.0.0-beta
  title: Verify
  contact:
    email: eng@wirescure.com
    name: WireSecure Engineering
  license: {}
  x-logo:
    url: 'https://raw.githubusercontent.com/wiresecure/verify-api/main/openapi/web/logo.png'
  description: |-
    The WireSecure verification API allows you to request confirmation of wire instructions from parties who must prove their identity.

    A demo is available showing how this functionality may be embedded within the [collection of subscriber documents](https://verify-demo.wiresecure.com/demo/button_collect) during the onboarding of a new fund.

    NOTE: This documentation is still under active discussion and development and things are likely to change before production release.
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
servers:
  - url: 'https://verify-api.wiresecure.com'
    description: PRODUCTION
  - url: 'https://verify-api-sandbox.wiresecure.com'
    description: SANDBOX
paths:
  /verify:
    parameters: []
    post:
      summary: Create a verification request
      operationId: post-verify
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: This is the ID you'll use to pull the results of this verification request and the verified instructions.
                  verificationLink:
                    type: string
                    description: The URL to use for verification.
                required:
                  - id
                  - verificationLink
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
              examples:
                Error message example:
                  value: 0210021 is not a valid ABA or SWIFT code
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      description: |-
        Create a request for verification/confirmation of identity and wire instructions. If wire instructions are already on file and provided through this endpoint, they will be shown to the individual and they will be asked to confirm that the instructions are valid.

        This method returns a link that can be used for verification. The intent is that this can either be opened in a new tab (if this API is being called while embedded in a web application) or sent via SMS or email.

        This method also returns an ID for this request which can be used by the `GET` method to fetch the results of this confirmation/verification.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email_address:
                  type: string
                phone_number:
                  type: string
                  description: The E164 compliant phone number for this individual
                  example: '+12125551234'
                metadata:
                  type: object
                  description: This metadata will be returned back when retrieving this verification is unused by WireSecure. It can be any valid JSON object.
                wire_instructions:
                  $ref: '#/components/schemas/WireInstructions'
              required:
                - name
                - email_address
            examples:
              example with instructions to be confirmed:
                value:
                  name: John Smith
                  email_address: john.smith@gmail.com
                  phone_number: '+12125551234'
                  metadata:
                    internal_id: JSMITH001
                  wire_instructions:
                    bank_id_code: '021000021'
                    name_on_account: SMITH FAMILY TRUST LLC
                    beneficiary_address: '3624 Dauphine St, New Orleans, LA 70117'
                    account_number: '103983019283'
                    ffc: FBO acct 3020449390-B
                    intermediary_bank_name: BANQUE DE SAVOIE S.A.
                    intermediary_bank_id_code: BSAVFR2C
                    intermediary_bank_id_code_type: SWIFT
                    intermediary_bank_account_number: '1120897764'
        description: ''
      deprecated: true
    get:
      summary: Retrieve verification results
      operationId: get-verify
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Confirmation'
              examples:
                example:
                  value:
                    id: qyiyyPTZB9g
                    client_metadata:
                      internal_id: '309182313'
                      group_id: ds839jdad
                    wire_instructions:
                      bank_name: JP MORGAN CHASE
                      bank_id_code: '021000021'
                      id_code_type: ABA
                      name_on_account: Smith Family Trust LLC
                      beneficiary_address: '3624 Dauphine St, New Orleans, LA 70117'
                      account_number: '103983019283'
                      ffc: FBO acct 3020449390-B
                      intermediary_bank_name: BANQUE DE SAVOIE S.A.
                      intermediary_bank_id_code: BSAVFR2C
                      intermediary_bank_id_code_type: SWIFT
                      intermediary_bank_account_number: '1120897764'
                      provided_by:
                        name: Ali Someperson
                        legal_name: ALLISON KATHRYN SOMEPERSON
                        email_address: alice@familyoffice.com
                        phone_number: '+12125551212'
                        status: PASSED
                        at: '2021-07-28 18:15 EST'
                        from: 'New York, NY USA'
                        verification_details:
                          mobile_provided: true
                          mobile_risk_score: 0.12
                          id_provided: true
                          id_risk_score: 0.08
                          name_match: 0.92
                          flags: []
                      confirmed_by:
                        name: John Smith
                        legal_name: JONATHAN WINGATE SMITH
                        email_address: john.smith@gmail.com
                        phone_number: '+12125551213'
                        status: PASSED
                        at: '2021-07-29 15:12 EST'
                        from: 'Metarie, LA USA'
                        verification_details:
                          mobile_provided: true
                          mobile_risk_score: 0.32
                          id_provided: true
                          id_risk_score: 0.18
                          name_match: 0.82
                          flags:
                            - Name on gov't issued ID is below match threshold
                            - Phone number is not associated with this individual
      description: Retrieve the instructions payload and details of the verification.
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: The verification request ID that was received after calling the POST method
          required: true
      deprecated: true
  /members:
    put:
      summary: Member Create
      operationId: put-members
      responses:
        '200':
          description: OK
      security:
        - api_key: []
      description: Create a new member and get a link to use for ID verification of the individual providing or confirming the requested items.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  name: Smith Family Trust
                  externalMetadata:
                    id: client-id-123
                    group_id: client-group-id-123
                    something_else: hi there
                  representatives:
                    - name: Victor Adminski
                      email: vadminski@familyoffices.test
                      phone: '+12125551234'
                  verifiableItems:
                    - type: wireinstructions
                      data:
                        nameOnAccount: SMITH FAMILY TRUST LLC
                        bankIdCode: '021000021'
                        bankAccountNumber: '1234567890'
              properties:
                name:
                  type: string
                  description: The name of this entity that is represented by the provided representative(s).
                  example: Smith Family Trust LLC
                externalMetadata:
                  type: object
                  description: Additional data passed back to the client with this member
                representatives:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  description: The parties that will be representing this member and providing the requested information. They will be asked to go through ID Verification.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        minLength: 1
                      email:
                        type: string
                        minLength: 1
                      phone:
                        type: string
                        example: '+12125551234'
                        pattern: '^\+[1-9]\d{1,14}$'
                        description: e.164 formatted phone number
                    required:
                      - name
                      - email
                verifiableItems:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        minLength: 1
                      data:
                        type: object
                    required:
                      - type
              required:
                - name
                - representatives
                - verifiableItems
            examples:
              example-1:
                value:
                  name: Smith Family Trust
                  externalMetadata:
                    id: client-id-123
                    group_id: client-group-id-123
                    something_else: hi there
                  representatives:
                    - name: Victor Adminski
                      email: vadminski@familyoffices.test
                      phone: '+12125551234'
                  verifiableItems:
                    - type: wireinstructions
                      data:
                        nameOnAccount: SMITH FAMILY TRUST LLC
                        bankIdCode: '021000021'
                        bankAccountNumber: '1234567890'
        description: ''
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
      description: The api key provided to you by WireSecure
  schemas:
    Confirmation:
      description: The results of a verification request.
      type: object
      x-examples:
        Example Confirmation Response:
          id: qyiyyPTZB9g
          client_metadata:
            internal_id: '309182313'
            group_id: ds839jdad
          wire_instructions:
            bank_name: JP MORGAN CHASE
            bank_id_code: '021000021'
            id_code_type: ABA
            name_on_account: Smith Family Trust LLC
            beneficiary_address: '3624 Dauphine St, New Orleans, LA 70117'
            account_number: '103983019283'
            ffc: FBO acct 3020449390-B
            intermediary_bank_name: BANQUE DE SAVOIE S.A.
            intermediary_bank_id_code: BSAVFR2C
            intermediary_bank_id_code_type: SWIFT
            intermediary_bank_account_number: '1120897764'
          provided_by:
            name: Ali Someperson
            legal_name: ALLISON KATHRYN SOMEPERSON
            email_address: alice@familyoffice.com
            phone_number: '+12125551212'
            status: PASSED
            at: '2021-07-28 18:15 EST'
            from: 'New York, NY USA'
            verification_details:
              mobile_provided: true
              mobile_risk_score: 0.12
              id_provided: true
              id_risk_score: 0.08
              name_match: 0.92
              flags: []
          confirmed_by:
            name: John Smith
            legal_name: JONATHAN WINGATE SMITH
            email_address: john.smith@gmail.com
            phone_number: '+12125551213'
            status: PASSED
            at: '2021-07-29 15:12 EST'
            from: 'Metarie, LA USA'
            verification_details:
              mobile_provided: true
              mobile_risk_score: 0.32
              id_provided: true
              id_risk_score: 0.18
              name_match: 0.82
              flags:
                - Name on gov't issued ID is below match threshold
                - Phone number is not associated with this individual
          value:
            id: qyiyyPTZB9g
            client_metadata:
              internal_id: '309182313'
              group_id: ds839jdad
            wire_instructions:
              bank_name: JP MORGAN CHASE
              bank_id_code: '021000021'
              id_code_type: ABA
              name_on_account: Smith Family Trust LLC
              beneficiary_address: '3624 Dauphine St, New Orleans, LA 70117'
              account_number: '103983019283'
              ffc: FBO acct 3020449390-B
              intermediary_bank_name: BANQUE DE SAVOIE S.A.
              intermediary_bank_id_code: BSAVFR2C
              intermediary_bank_id_code_type: SWIFT
              intermediary_bank_account_number: '1120897764'
            provided_by:
              name: Ali Someperson
              legal_name: ALLISON KATHRYN SOMEPERSON
              email_address: alice@familyoffice.com
              phone_number: '+12125551212'
              status: PASSED
              at: '2021-07-28 18:15 EST'
              from: 'New York, NY USA'
              verification_details:
                mobile_provided: true
                mobile_risk_score: 0.12
                id_provided: true
                id_risk_score: 0.08
                name_match: 0.92
                flags: []
            confirmed_by:
              name: John Smith
              legal_name: JONATHAN WINGATE SMITH
              email_address: john.smith@gmail.com
              phone_number: '+12125551213'
              status: PASSED
              at: '2021-07-29 15:12 EST'
              from: 'Metarie, LA USA'
              verification_details:
                mobile_provided: true
                mobile_risk_score: 0.32
                id_provided: true
                id_risk_score: 0.18
                name_match: 0.82
                flags:
                  - Name on gov't issued ID is below match threshold
                  - Phone number is not associated with this individual
      properties:
        id:
          type: string
          minLength: 1
        client_metadata:
          type: object
          description: 'If any metadata was passed in with this request, it will be returned in this field'
        wire_instructions:
          $ref: '#/components/schemas/WireInstructions'
        provided_by:
          $ref: '#/components/schemas/Verification'
        confirmed_by:
          $ref: '#/components/schemas/Verification'
      required:
        - id
        - wire_instructions
        - provided_by
        - confirmed_by
    WireInstructions:
      description: 'Information required to generate a wire transfer request. If an intermediary bank is to be used, that information is also provided.'
      type: object
      x-examples:
        Example Wire Instructions:
          bank_name: JP MORGAN CHASE
          bank_id_code: '021000021'
          id_code_type: ABA
          name_on_account: Smith Family Trust LLC
          beneficiary_address: '3624 Dauphine St, New Orleans, LA 70117'
          account_number: '103983019283'
          ffc: FBO acct 3020449390-B
          intermediary_bank_name: BANQUE DE SAVOIE S.A.
          intermediary_bank_id_code: BSAVFR2C
          intermediary_bank_id_code_type: SWIFT
          intermediary_bank_account_number: '1120897764'
          value:
            bank_name: JP MORGAN CHASE
            bank_id_code: '021000021'
            id_code_type: ABA
            name_on_account: Smith Family Trust LLC
            beneficiary_address: '3624 Dauphine St, New Orleans, LA 70117'
            account_number: '103983019283'
            ffc: FBO acct 3020449390-B
            intermediary_bank_name: BANQUE DE SAVOIE S.A.
            intermediary_bank_id_code: BSAVFR2C
            intermediary_bank_id_code_type: SWIFT
            intermediary_bank_account_number: '1120897764'
      properties:
        bank_id_code:
          type: string
          description: The routing number for the bank (ABA or SWIFT)
          example: JP MORGAN CHASE
        bank_name:
          type: string
          description: The bank entity's legal name
        id_code_type:
          type: string
          description: '''ABA'' or ''SWIFT'''
          enum:
            - ABA
            - SWIFT
        name_on_account:
          type: string
          example: SMITH FAMILY TRUST LLC
          description: The name associated with this account
        beneficiary_address:
          type: string
          example: '3624 Dauphine St, New Orleans, LA 70117'
          description: The address associated witht this account
        account_number:
          type: string
          description: 'The account number '
        ffc:
          type: string
          description: For Further Credit information
        intermediary_bank_name:
          type: string
        intermediary_bank_id_code:
          type: string
        intermediary_bank_id_code_type:
          type: string
        intermediary_bank_account_number:
          type: string
      required:
        - bank_id_code
        - bank_name
        - id_code_type
        - name_on_account
        - beneficiary_address
        - account_number
    Verification:
      description: ''
      type: object
      x-examples:
        example-1:
          name: Ali Someperson
          legal_name: ALLISON KATHRYN SOMEPERSON
          email_address: alice@familyoffice.com
          phone_number: '+12125551212'
          status: PASSED
          at: '2021-07-28 18:15 EST'
          from: 'New York, NY USA'
          verification_details:
            mobile_provided: true
            mobile_risk_score: 0.12
            id_provided: true
            id_risk_score: 0.08
            name_match: 0.92
            flags: []
      properties:
        name:
          type: string
          description: The name of the party who was expected to go through this verification
          example: John Smith
        legal_name:
          type: string
          description: The name as it appears on this person's government issued ID
          example: JONATHAN WINGATE SMITH
        email_address:
          type: string
          description: The email address that was provided to us for this individual
        phone_number:
          type: string
          description: 'The E164 compliant phone number for this individual, provided by the individual during verification'
          example: '+12125551234'
        status:
          type: string
          enum:
            - PASSED
            - PENDING
            - FAILED
          description: The current status of this verification.
        at:
          type: string
          description: The timestamp of when this verification occurred
        from:
          type: string
          description: Coarse location information for where this verification occured
          example: 'Red Bank, NJ USA'
        verification_details:
          type: object
          required:
            - mobile_provided
            - id_provided
          properties:
            mobile_provided:
              type: boolean
              description: Indicates if a mobile number was provided for verification
            mobile_risk_score:
              type: number
              minimum: 0
              maximum: 1
              description: 'If a mobile number was provided for verification, this is the risk assessment of that number (lower is better).'
            id_provided:
              type: boolean
              description: Indicates whether or not an ID was evaluated during the course of this verification
            id_risk_score:
              type: number
              minimum: 0
              maximum: 1
              description: 'If a government issued ID was provided for verification, this is the risk assessment of that evaluation (lower is better).'
            name_match:
              type: number
              description: A measure of how closely the name provided matched the name on the individuals government issued ID
              minimum: 0
              maximum: 1
              example: 0.89
            flags:
              type: array
              description: An optional list of flags that were triggered during the verification
              items:
                type: string
                example: Phone number is not associated with this individual
      required:
        - name
        - email_address
        - phone_number
        - status
        - at
        - from
        - verification_details
  examples: {}
security:
  - api_key: []
tags:
  - name: Verify
